/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thecaffeinefix;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Mackson
 */
public class Breakfast extends javax.swing.JFrame {

    /**
     * Creates new form Breakfast
     */
    public Breakfast() {
        initComponents();
    }
    
    public boolean validation(){
        String username,total;
        username = txtusername.getText();
        
      
        if(username.equals("")){
            JOptionPane.showMessageDialog(this,"PLEASE ENTER THE USERNAME");
            return false;
        }
        
        return true;
    }
    
    public void bill(){
        
        double total,subtotal=0,tax;
        final double taxrate= .08;
        
        if (chkame.isSelected()){
            subtotal = subtotal + 210;
        }if (chkcap.isSelected()){
            subtotal = subtotal + 225;
        }if (chkmoc.isSelected()){
            subtotal = subtotal + 220;
        }if (chkegg.isSelected()){
            subtotal = subtotal + 180;
        }if (chkoat.isSelected()){
            subtotal = subtotal + 200;
        }if (chkpoh.isSelected()){
            subtotal = subtotal + 180;
        }if (chkdar.isSelected()){
            subtotal = subtotal + 200;
        }if (chkass.isSelected()){
            subtotal = subtotal + 210;
        }if (chkcre.isSelected()){
            subtotal = subtotal + 220;
        }
        
        subtxt.setText(Double.toString(subtotal));
        subtotal = Double.parseDouble(subtxt.getText());
        tax = subtotal * taxrate;
        total = tax + subtotal;
        
        taxtxt.setText(Double.toString(tax));
        totaltxt.setText(Double.toString(total));
        
    }
    
    public void clearbill(){
        chkame.setSelected(false);
        chkass.setSelected(false);
        chkcap.setSelected(false);
        chkcre.setSelected(false);
        chkdar.setSelected(false);
        chkegg.setSelected(false);
        chkmoc.setSelected(false);
        chkoat.setSelected(false);
        chkpoh.setSelected(false);
        subtxt.setText("");
        taxtxt.setText("");
        totaltxt.setText("");
    }
    
    public void insertintodb(){
        
        String americano = "No";
        String cappucino = "No";
        String mocha = "No";
        String egg_toast = "No";
        String oats = "No";
        String poha = "No";
        String darjeeling = "No";
        String assam = "No";
        String cream_tea = "No";
        String total;
        String username;
        
        total = totaltxt.getText();
        username = txtusername.getText();
        
        if(chkame.isSelected())
        {
            americano = "Yes";
        }
        if(chkcap.isSelected())
        {
            cappucino = "Yes";
        }
        if(chkmoc.isSelected())
        {
            mocha = "Yes";
        }
        if(chkegg.isSelected())
        {
            egg_toast = "Yes";
        }
        if(chkoat.isSelected())
        {
            oats = "Yes";
        }
        if(chkpoh.isSelected())
        {
            poha = "Yes";
        }
        if(chkdar.isSelected())
        {
            darjeeling = "Yes";
        }
        if(chkass.isSelected())
        {
            assam = "Yes";
        }
        if(chkcre.isSelected())
        {
            cream_tea = "Yes";
        }
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/breakfast_db","root","root");
            java.sql.Statement st=con.createStatement();
            String sql="insert into bf_order values('"+americano+"','"+cappucino+"','"+mocha+"','"+egg_toast+"','"+oats+"','"+poha+"','"+darjeeling+"','"+assam+"','"+cream_tea+"','"+total+"','"+username+"')";
            st.execute(sql);
            JOptionPane.showMessageDialog(this,"ORDER PLACED");
        } 
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(this,e.getMessage());
            
        }
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkame = new javax.swing.JCheckBox();
        chkcap = new javax.swing.JCheckBox();
        chkmoc = new javax.swing.JCheckBox();
        chkdar = new javax.swing.JCheckBox();
        chkass = new javax.swing.JCheckBox();
        chkcre = new javax.swing.JCheckBox();
        chkegg = new javax.swing.JCheckBox();
        chkoat = new javax.swing.JCheckBox();
        chkpoh = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subtxt = new javax.swing.JTextField();
        taxtxt = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblconfor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblclror = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblsee = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(826, 597));

        jPanel1.setBackground(new java.awt.Color(16, 34, 63));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 67, 71));
        jLabel2.setText("COFFEE");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 67, 71));
        jLabel1.setText("TEA");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 67, 71));
        jLabel3.setText("BREAKFAST");

        chkame.setBackground(new java.awt.Color(16, 34, 63));
        chkame.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkame.setForeground(new java.awt.Color(244, 244, 244));
        chkame.setText("Americano......................................................................210/-");
        chkame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkameActionPerformed(evt);
            }
        });

        chkcap.setBackground(new java.awt.Color(16, 34, 63));
        chkcap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkcap.setForeground(new java.awt.Color(244, 244, 244));
        chkcap.setText("Cappucino.......................................................................225/-");
        chkcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcapActionPerformed(evt);
            }
        });

        chkmoc.setBackground(new java.awt.Color(16, 34, 63));
        chkmoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkmoc.setForeground(new java.awt.Color(244, 244, 244));
        chkmoc.setText("Mocha..............................................................................220/-");
        chkmoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmocActionPerformed(evt);
            }
        });

        chkdar.setBackground(new java.awt.Color(16, 34, 63));
        chkdar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkdar.setForeground(new java.awt.Color(244, 244, 244));
        chkdar.setText("Darjeeling.....................................................................200/-");
        chkdar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkdarActionPerformed(evt);
            }
        });

        chkass.setBackground(new java.awt.Color(16, 34, 63));
        chkass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkass.setForeground(new java.awt.Color(244, 244, 244));
        chkass.setText("Assam...........................................................................210/-");
        chkass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkassActionPerformed(evt);
            }
        });

        chkcre.setBackground(new java.awt.Color(16, 34, 63));
        chkcre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkcre.setForeground(new java.awt.Color(244, 244, 244));
        chkcre.setText("Cream Tea....................................................................220/-");
        chkcre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcreActionPerformed(evt);
            }
        });

        chkegg.setBackground(new java.awt.Color(16, 34, 63));
        chkegg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkegg.setForeground(new java.awt.Color(244, 244, 244));
        chkegg.setText("Egg Toast......................................................................180/-");
        chkegg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkeggActionPerformed(evt);
            }
        });

        chkoat.setBackground(new java.awt.Color(16, 34, 63));
        chkoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkoat.setForeground(new java.awt.Color(244, 244, 244));
        chkoat.setText("Oats...............................................................................200/-");
        chkoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkoatActionPerformed(evt);
            }
        });

        chkpoh.setBackground(new java.awt.Color(16, 34, 63));
        chkpoh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkpoh.setForeground(new java.awt.Color(244, 244, 244));
        chkpoh.setText("Poha...............................................................................180/-");
        chkpoh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkpohActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 67, 71));
        jLabel4.setText("TOTAL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 67, 71));
        jLabel5.setText("TAX");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 67, 71));
        jLabel6.setText("SUB-TOTAL");

        subtxt.setBackground(new java.awt.Color(16, 34, 63));
        subtxt.setForeground(new java.awt.Color(255, 255, 255));
        subtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxtxt.setBackground(new java.awt.Color(16, 34, 63));
        taxtxt.setForeground(new java.awt.Color(255, 255, 255));
        taxtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totaltxt.setBackground(new java.awt.Color(16, 34, 63));
        totaltxt.setForeground(new java.awt.Color(255, 255, 255));
        totaltxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(233, 67, 71));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblconfor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblconfor.setForeground(new java.awt.Color(16, 34, 63));
        lblconfor.setText("      CONFIRM ORDER");
        lblconfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblconforMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblconfor, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblconfor, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(16, 34, 63));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblclror.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblclror.setForeground(new java.awt.Color(233, 67, 71));
        lblclror.setText("  CLEAR ORDER");
        lblclror.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 67, 71)));
        lblclror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclrorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblclror, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblclror, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(16, 34, 63));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblsee.setBackground(new java.awt.Color(16, 34, 63));
        lblsee.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblsee.setForeground(new java.awt.Color(233, 67, 71));
        lblsee.setText("       SEE BILL");
        lblsee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 67, 71)));
        lblsee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblseeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtusername.setBackground(new java.awt.Color(16, 34, 63));
        txtusername.setForeground(new java.awt.Color(244, 244, 244));
        txtusername.setBorder(null);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(233, 67, 71));
        jSeparator7.setForeground(new java.awt.Color(233, 67, 71));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 67, 71));
        jLabel7.setText(" Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chkoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkame)
                                .addComponent(chkcap)
                                .addComponent(chkmoc)
                                .addComponent(jLabel2))
                            .addGap(34, 34, 34))
                        .addComponent(chkegg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(chkpoh, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkdar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkcre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtxt)
                            .addComponent(taxtxt)
                            .addComponent(totaltxt)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkdar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkcap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkmoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkcre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkegg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(taxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkpoh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        jMenuBar1.setBackground(new java.awt.Color(233, 67, 71));

        jMenu1.setText("Breakfast Details");
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("COFFEE");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenu2.setText("Americano");

        jMenuItem2.setText("An Americano has a much robust flavor & is a little bitter. An Americano is espresso topped up with hot water.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.add(jMenu2);

        jMenu3.setText("Cappucino");

        jMenuItem5.setText("A cappuccino is a very precise espresso based drink with steamed milk and milk foam.");
        jMenu3.add(jMenuItem5);

        jMenu1.add(jMenu3);

        jMenu4.setText("Mocha");

        jMenuItem6.setText("Mocha is a high quality type of coffee made from a specific coffee bean and it is much stronger.");
        jMenu4.add(jMenuItem6);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator3);

        jMenuItem3.setText("TEA");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator4);

        jMenu5.setText("Darjeeling");

        jMenuItem7.setText("Darjeeling tea, often called the fine wine of teas, is famous for its special aroma & is preferred by connoisseurs around the world");
        jMenu5.add(jMenuItem7);

        jMenu1.add(jMenu5);

        jMenu6.setText("Assam");

        jMenuItem8.setText("While there is no cure for cancer, a cup of Assam tea would keep you hydrated and fight against cancer.");
        jMenu6.add(jMenuItem8);

        jMenu1.add(jMenu6);

        jMenu7.setText("Cream Tea");

        jMenuItem9.setText("Cream tea refers to practice of having tea with scones and clotted cream. ");
        jMenu7.add(jMenuItem9);

        jMenu1.add(jMenu7);
        jMenu1.add(jSeparator5);

        jMenuItem4.setText("BREAKFAST");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator6);

        jMenu8.setText("Egg Toast");

        jMenuItem10.setText("Whether they are scrambled, poached, boiled or fried, eggs are a great option on wholemeal toast.");
        jMenu8.add(jMenuItem10);

        jMenu1.add(jMenu8);

        jMenu9.setText("Oats");

        jMenuItem11.setText("Oatmeal is a type of porridge made from milled, steel-cut, or rolled oat grains and is served along with hot milk in it.");
        jMenu9.add(jMenuItem11);

        jMenu1.add(jMenu9);

        jMenu10.setText("Poha");

        jMenuItem12.setText("Flattened rice is tempered with spices and onions making it the perfect way to start the day.");
        jMenu10.add(jMenuItem12);

        jMenu1.add(jMenu10);

        jMenuBar1.add(jMenu1);

        jMenu11.setText("More..");

        jMenuItem13.setText("Go Back");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem13);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkameActionPerformed

    private void chkcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcapActionPerformed

    private void chkmocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkmocActionPerformed

    private void chkdarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkdarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkdarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void chkeggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkeggActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkeggActionPerformed

    private void chkoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkoatActionPerformed

    private void chkpohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkpohActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkpohActionPerformed

    private void chkcreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcreActionPerformed

    private void chkassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkassActionPerformed

    private void lblseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblseeMouseClicked
        // SEE BILL 
        bill();
    }//GEN-LAST:event_lblseeMouseClicked

    private void lblclrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclrorMouseClicked
        // CLEARS THE BILL
        clearbill();
    }//GEN-LAST:event_lblclrorMouseClicked

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // GO BACK
        dispose();
        new Main_UI().setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void lblconforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblconforMouseClicked
        // PLACE ORDER
        if(validation()==true)
        {
        bill();
        insertintodb();
        
        }
    }//GEN-LAST:event_lblconforMouseClicked

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Breakfast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkame;
    private javax.swing.JCheckBox chkass;
    private javax.swing.JCheckBox chkcap;
    private javax.swing.JCheckBox chkcre;
    private javax.swing.JCheckBox chkdar;
    private javax.swing.JCheckBox chkegg;
    private javax.swing.JCheckBox chkmoc;
    private javax.swing.JCheckBox chkoat;
    private javax.swing.JCheckBox chkpoh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblclror;
    private javax.swing.JLabel lblconfor;
    private javax.swing.JLabel lblsee;
    private javax.swing.JTextField subtxt;
    private javax.swing.JTextField taxtxt;
    private javax.swing.JTextField totaltxt;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
