/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thecaffeinefix;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Mackson
 */
public class Dessert extends javax.swing.JFrame {

    /**
     * Creates new form Dessert
     */
    public Dessert() {
        initComponents();
    }
    
    public boolean validation(){
        String username,total;
        username = txtusername.getText();
        
      
        if(username.equals("")){
            JOptionPane.showMessageDialog(this,"PLEASE ENTER THE USERNAME");
            return false;
        }
        
        return true;
    }
    
    public void insertintodb(){
        
        String blueberry_choco = "No";
        String exp_choco = "No";
        String red_velvet = "No";
        String cookie_dl = "No";
        String sundae = "No";
        String tiramissu = "No";
        String cheese_ck = "No";
        String lemon_ck = "No";
        String rose_ck = "No";
        String total;
        String username;
        
        total = totaltxt.getText();
        username = txtusername.getText();
        
        if(chkblu.isSelected())
        {
            blueberry_choco = "Yes";
        }
        if(chkexp.isSelected())
        {
            exp_choco = "Yes";
        }
        if(chkred.isSelected())
        {
            red_velvet = "Yes";
        }
        if(chkcoo.isSelected())
        {
            cookie_dl = "Yes";
        }
        if(chksun.isSelected())
        {
            sundae = "Yes";
        }
        if(chktir.isSelected())
        {
            tiramissu = "Yes";
        }
        if(chkche.isSelected())
        {
            cheese_ck = "Yes";
        }
        if(chklem.isSelected())
        {
            lemon_ck = "Yes";
        }
        if(chkros.isSelected())
        {
            rose_ck = "Yes";
        }
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dessert_db","root","root");
            java.sql.Statement st=con.createStatement();
            String sql="insert into d_order values('"+blueberry_choco+"','"+exp_choco+"','"+red_velvet+"','"+cookie_dl+"','"+sundae+"','"+tiramissu+"','"+cheese_ck+"','"+lemon_ck+"','"+rose_ck+"','"+username+"','"+total+"')";
            st.execute(sql);
            JOptionPane.showMessageDialog(this,"ORDER PLACED");
        } 
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(this,e.getMessage());
            
        }
        
        
        
    }
    
    public void bill(){
        
        double total,subtotal=0,tax;
        final double taxrate= .08;
        
        if (chkblu.isSelected()){
            subtotal = subtotal + 210;
        }if (chkche.isSelected()){
            subtotal = subtotal + 200;
        }if (chkcoo.isSelected()){
            subtotal = subtotal + 250;
        }if (chkexp.isSelected()){
            subtotal = subtotal + 225;
        }if (chklem.isSelected()){
            subtotal = subtotal + 210;
        }if (chkred.isSelected()){
            subtotal = subtotal + 220;
        }if (chkros.isSelected()){
            subtotal = subtotal + 220;
        }if (chksun.isSelected()){
            subtotal = subtotal + 200;
        }if (chktir.isSelected()){
            subtotal = subtotal + 180;
        }
        
        subtxt.setText(Double.toString(subtotal));
        subtotal = Double.parseDouble(subtxt.getText());
        tax = subtotal * taxrate;
        total = tax + subtotal;
        
        taxtxt.setText(Double.toString(tax));
        totaltxt.setText(Double.toString(total));
        
    }
    
    public void clearbill(){
        chkblu.setSelected(false);
        chkche.setSelected(false);
        chkcoo.setSelected(false);
        chkexp.setSelected(false);
        chklem.setSelected(false);
        chkred.setSelected(false);
        chkros.setSelected(false);
        chksun.setSelected(false);
        chktir.setSelected(false);
        subtxt.setText("");
        taxtxt.setText("");
        totaltxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkblu = new javax.swing.JCheckBox();
        chkexp = new javax.swing.JCheckBox();
        chkred = new javax.swing.JCheckBox();
        chkche = new javax.swing.JCheckBox();
        chklem = new javax.swing.JCheckBox();
        chkros = new javax.swing.JCheckBox();
        chkcoo = new javax.swing.JCheckBox();
        chksun = new javax.swing.JCheckBox();
        chktir = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subtxt = new javax.swing.JTextField();
        taxtxt = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblconfor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblclror = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblsee = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 34, 63));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 67, 71));
        jLabel2.setText("WAFFLES");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 67, 71));
        jLabel1.setText("CAKES");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 67, 71));
        jLabel3.setText("ICE - CREAM");

        chkblu.setBackground(new java.awt.Color(16, 34, 63));
        chkblu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkblu.setForeground(new java.awt.Color(244, 244, 244));
        chkblu.setText("Blueberry White Chocolate......................................210/-");
        chkblu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbluActionPerformed(evt);
            }
        });

        chkexp.setBackground(new java.awt.Color(16, 34, 63));
        chkexp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkexp.setForeground(new java.awt.Color(244, 244, 244));
        chkexp.setText("Express Chocolate.........................................................225/-");
        chkexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkexpActionPerformed(evt);
            }
        });

        chkred.setBackground(new java.awt.Color(16, 34, 63));
        chkred.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkred.setForeground(new java.awt.Color(244, 244, 244));
        chkred.setText("Red Velvet........................................................................220/-");
        chkred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkredActionPerformed(evt);
            }
        });

        chkche.setBackground(new java.awt.Color(16, 34, 63));
        chkche.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkche.setForeground(new java.awt.Color(244, 244, 244));
        chkche.setText("Cheese Cake...............................................................200/-");
        chkche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcheActionPerformed(evt);
            }
        });

        chklem.setBackground(new java.awt.Color(16, 34, 63));
        chklem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chklem.setForeground(new java.awt.Color(244, 244, 244));
        chklem.setText("Lemon Cake................................................................210/-");
        chklem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chklemActionPerformed(evt);
            }
        });

        chkros.setBackground(new java.awt.Color(16, 34, 63));
        chkros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkros.setForeground(new java.awt.Color(244, 244, 244));
        chkros.setText("Rose Cake....................................................................220/-");
        chkros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkrosActionPerformed(evt);
            }
        });

        chkcoo.setBackground(new java.awt.Color(16, 34, 63));
        chkcoo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkcoo.setForeground(new java.awt.Color(244, 244, 244));
        chkcoo.setText("Cookie Delight...........................................................250/-");
        chkcoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcooActionPerformed(evt);
            }
        });

        chksun.setBackground(new java.awt.Color(16, 34, 63));
        chksun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chksun.setForeground(new java.awt.Color(244, 244, 244));
        chksun.setText("Sundae...........................................................................200/-");
        chksun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksunActionPerformed(evt);
            }
        });

        chktir.setBackground(new java.awt.Color(16, 34, 63));
        chktir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chktir.setForeground(new java.awt.Color(244, 244, 244));
        chktir.setText("Tiramissu.......................................................................180/-");
        chktir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chktirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 67, 71));
        jLabel4.setText("TOTAL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 67, 71));
        jLabel5.setText("TAX");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 67, 71));
        jLabel6.setText("SUB-TOTAL");

        subtxt.setBackground(new java.awt.Color(16, 34, 63));
        subtxt.setForeground(new java.awt.Color(255, 255, 255));
        subtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxtxt.setBackground(new java.awt.Color(16, 34, 63));
        taxtxt.setForeground(new java.awt.Color(255, 255, 255));
        taxtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totaltxt.setBackground(new java.awt.Color(16, 34, 63));
        totaltxt.setForeground(new java.awt.Color(255, 255, 255));
        totaltxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(233, 67, 71));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblconfor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblconfor.setForeground(new java.awt.Color(16, 34, 63));
        lblconfor.setText("      CONFIRM ORDER");
        lblconfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblconforMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblconfor, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblconfor, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(16, 34, 63));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblclror.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblclror.setForeground(new java.awt.Color(233, 67, 71));
        lblclror.setText(" CLEAR ORDER");
        lblclror.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 67, 71)));
        lblclror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclrorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblclror, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblclror, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(16, 34, 63));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblsee.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblsee.setForeground(new java.awt.Color(233, 67, 71));
        lblsee.setText("     SEE BILL");
        lblsee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 67, 71)));
        lblsee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblseeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 67, 71));
        jLabel7.setText("   Username");

        txtusername.setBackground(new java.awt.Color(16, 34, 63));
        txtusername.setForeground(new java.awt.Color(244, 244, 244));
        txtusername.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(233, 67, 71));
        jSeparator7.setForeground(new java.awt.Color(233, 67, 71));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chksun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkblu)
                                        .addComponent(chkexp)
                                        .addComponent(chkred)
                                        .addComponent(jLabel2))
                                    .addGap(34, 34, 34))
                                .addComponent(chkcoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(chktir, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chklem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(125, 125, 125)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtxt)
                                    .addComponent(totaltxt)
                                    .addComponent(taxtxt)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(57, 102, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7)
                            .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(358, 358, 358))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkblu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkche, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkexp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chklem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkred, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkcoo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(taxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chksun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chktir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jMenuBar1.setBackground(new java.awt.Color(233, 67, 71));

        jMenu1.setText("Dessert Details");
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("WAFFLES");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenu2.setText("Blueberry White Chocolate");

        jMenuItem4.setText(" The pop of fresh blueberries and surprise of white chocolate .");
        jMenu2.add(jMenuItem4);

        jMenu1.add(jMenu2);

        jMenu3.setText("Express Chocolate");

        jMenuItem5.setText(" This has just a hint of chocolate, cinnamon, vanilla and LOTS of yum. ");
        jMenu3.add(jMenuItem5);

        jMenu1.add(jMenu3);

        jMenu4.setText("Red Velvet");

        jMenuItem6.setText("Red velvet waffles topped with a cream cheese glaze, whipped cream, and strawberries is a decadent treat.");
        jMenu4.add(jMenuItem6);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator3);

        jMenuItem2.setText("CAKES");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator4);

        jMenu5.setText("Cheese Cake");

        jMenuItem7.setText(" A rich sweet tart made with cream and soft cheese on a biscuit base.");
        jMenu5.add(jMenuItem7);

        jMenu1.add(jMenu5);

        jMenu6.setText("Lemon Cake");

        jMenuItem8.setText("Lemon cake is a dense, flavorful and very popular cake. Lemon is used to provide its unique flavor ");
        jMenu6.add(jMenuItem8);

        jMenu1.add(jMenu6);

        jMenu7.setText("Rose Cake");

        jMenuItem9.setText(" Made with rose water and a sweet buttercream frosting, this delicate cake is perfect. ");
        jMenu7.add(jMenuItem9);

        jMenu1.add(jMenu7);
        jMenu1.add(jSeparator5);

        jMenuItem3.setText("ICE - CREAM");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator6);

        jMenu8.setText("Cookie Delight");

        jMenuItem10.setText("Rich vanilla and chocolate ice cream swirled with sea salt cookie fudge with chunks of cookie dough and brownie pieces.");
        jMenu8.add(jMenuItem10);

        jMenu1.add(jMenu8);

        jMenu9.setText("Sundae");

        jMenuItem11.setText("This is a sundae served in a tall glass filled with layers of ice cream or yogurt, gelatine, and flavorings.");
        jMenu9.add(jMenuItem11);

        jMenu1.add(jMenu9);

        jMenu10.setText("Tiramissu");

        jMenuItem12.setText("An Italian dessert consisting of layers of sponge cake soaked in coffee &  with powdered chocolate & mascarpone cheese.");
        jMenu10.add(jMenuItem12);

        jMenu1.add(jMenu10);

        jMenuBar1.add(jMenu1);

        jMenu11.setText("More...");

        jMenuItem13.setText("Go Back");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem13);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkbluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbluActionPerformed

    private void chkexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkexpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkexpActionPerformed

    private void chkredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkredActionPerformed

    private void chkcheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcheActionPerformed

    private void chklemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chklemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chklemActionPerformed

    private void chkrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkrosActionPerformed

    private void chkcooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcooActionPerformed

    private void chksunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chksunActionPerformed

    private void chktirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chktirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chktirActionPerformed

    private void lblseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblseeMouseClicked
        // SEE BILL
        bill();
    }//GEN-LAST:event_lblseeMouseClicked

    private void lblclrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclrorMouseClicked
        // CLEARS BILL
        clearbill();
    }//GEN-LAST:event_lblclrorMouseClicked

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // GO BACK
        dispose();
        new Main_UI().setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void lblconforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblconforMouseClicked
        // PLACE ORDER
        if(validation()==true)
        {
        bill();
        insertintodb();
        
        }
    
    }//GEN-LAST:event_lblconforMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dessert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dessert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkblu;
    private javax.swing.JCheckBox chkche;
    private javax.swing.JCheckBox chkcoo;
    private javax.swing.JCheckBox chkexp;
    private javax.swing.JCheckBox chklem;
    private javax.swing.JCheckBox chkred;
    private javax.swing.JCheckBox chkros;
    private javax.swing.JCheckBox chksun;
    private javax.swing.JCheckBox chktir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblclror;
    private javax.swing.JLabel lblconfor;
    private javax.swing.JLabel lblsee;
    private javax.swing.JTextField subtxt;
    private javax.swing.JTextField taxtxt;
    private javax.swing.JTextField totaltxt;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
