/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thecaffeinefix;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Mackson
 */
public class Lunch extends javax.swing.JFrame {

    /**
     * Creates new form Lunch
     */
    public Lunch() {
        initComponents();
    }
    
    public boolean validation(){
        String username,total;
        username = txtusername.getText();
        
      
        if(username.equals("")){
            JOptionPane.showMessageDialog(this,"PLEASE ENTER THE USERNAME");
            return false;
        }
        
        return true;
    }
    
    public void insertintodb(){
        
        String triple = "No";
        String egg_schezwan = "No";
        String cor_rice_gry = "No";
        String paneer_tikka = "No";
        String matar = "No";
        String korma = "No";
        String cheese_brg = "No";
        String cheese_grl_swch = "No";
        String nacho_pizza = "No";
        String total;
        String username;
        
        total = totaltxt.getText();
        username = txtusername.getText();
        
        if(chktri.isSelected())
        {
            triple = "Yes";
        }
        if(chkegg_l.isSelected())
        {
            egg_schezwan = "Yes";
        }
        if(chkcor.isSelected())
        {
            cor_rice_gry = "Yes";
        }
        if(chkpan.isSelected())
        {
            paneer_tikka = "Yes";
        }
        if(chkmat.isSelected())
        {
            matar = "Yes";
        }
        if(chkkor.isSelected())
        {
            korma = "Yes";
        }
        if(chkand.isSelected())
        {
            cheese_brg = "Yes";
        }
        if(chkgri.isSelected())
        {
            cheese_grl_swch = "Yes";
        }
        if(chk3ch.isSelected())
        {
            nacho_pizza = "Yes";
        }
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lunch_db","root","root");
            java.sql.Statement st=con.createStatement();
            String sql="insert into l_order values('"+triple+"','"+egg_schezwan+"','"+cor_rice_gry+"','"+paneer_tikka+"','"+matar+"','"+korma+"','"+cheese_brg+"','"+cheese_grl_swch+"','"+nacho_pizza+"','"+username+"','"+total+"')";
            st.execute(sql);
            JOptionPane.showMessageDialog(this,"ORDER PLACED");
        } 
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(this,e.getMessage());
            
        }
        
        
        
    }
    
    public void bill(){
        
        double total,subtotal=0,tax;
        final double taxrate= .08;
        
        if (chk3ch.isSelected()){
            subtotal = subtotal + 520;
        }if (chkand.isSelected()){
            subtotal = subtotal + 150;
        }if (chkcor.isSelected()){
            subtotal = subtotal + 420;
        }if (chkegg_l.isSelected()){
            subtotal = subtotal + 250;
        }if (chkgri.isSelected()){
            subtotal = subtotal + 110;
        }if (chkkor.isSelected()){
            subtotal = subtotal + 220;
        }if (chkmat.isSelected()){
            subtotal = subtotal + 120;
        }if (chkpan.isSelected()){
            subtotal = subtotal + 380;
        }if (chktri.isSelected()){
            subtotal = subtotal + 350;
        }
        
        subtxt.setText(Double.toString(subtotal));
        subtotal = Double.parseDouble(subtxt.getText());
        tax = subtotal * taxrate;
        total = tax + subtotal;
        
        taxtxt.setText(Double.toString(tax));
        totaltxt.setText(Double.toString(total));
        
    }
    
    public void clearbill(){
        chk3ch.setSelected(false);
        chkand.setSelected(false);
        chkcor.setSelected(false);
        chkegg_l.setSelected(false);
        chkgri.setSelected(false);
        chkkor.setSelected(false);
        chkmat.setSelected(false);
        chkpan.setSelected(false);
        chktri.setSelected(false);
        subtxt.setText("");
        taxtxt.setText("");
        totaltxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chktri = new javax.swing.JCheckBox();
        chkegg_l = new javax.swing.JCheckBox();
        chkcor = new javax.swing.JCheckBox();
        chkand = new javax.swing.JCheckBox();
        chkgri = new javax.swing.JCheckBox();
        chk3ch = new javax.swing.JCheckBox();
        chkpan = new javax.swing.JCheckBox();
        chkmat = new javax.swing.JCheckBox();
        chkkor = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subtxt = new javax.swing.JTextField();
        taxtxt = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblconfor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblclror = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblsee = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 34, 63));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 67, 71));
        jLabel2.setText("LUNCH");

        chktri.setBackground(new java.awt.Color(16, 34, 63));
        chktri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chktri.setForeground(new java.awt.Color(244, 244, 244));
        chktri.setText("Veg Triple Fried Rice...................................................350/-");
        chktri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chktriActionPerformed(evt);
            }
        });

        chkegg_l.setBackground(new java.awt.Color(16, 34, 63));
        chkegg_l.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkegg_l.setForeground(new java.awt.Color(244, 244, 244));
        chkegg_l.setText("Egg Schezwan Fried Rice...........................................250/-");
        chkegg_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkegg_lActionPerformed(evt);
            }
        });

        chkcor.setBackground(new java.awt.Color(16, 34, 63));
        chkcor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkcor.setForeground(new java.awt.Color(244, 244, 244));
        chkcor.setText("Chicken Coriander Rice with Gravy......................420/-");
        chkcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkcorActionPerformed(evt);
            }
        });

        chkand.setBackground(new java.awt.Color(16, 34, 63));
        chkand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkand.setForeground(new java.awt.Color(244, 244, 244));
        chkand.setText("Chicken and Cheese Burger.....................................150/-");
        chkand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkandActionPerformed(evt);
            }
        });

        chkgri.setBackground(new java.awt.Color(16, 34, 63));
        chkgri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkgri.setForeground(new java.awt.Color(244, 244, 244));
        chkgri.setText("Veg Cheese Grilled Sandwich..................................110/-");
        chkgri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkgriActionPerformed(evt);
            }
        });

        chk3ch.setBackground(new java.awt.Color(16, 34, 63));
        chk3ch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk3ch.setForeground(new java.awt.Color(244, 244, 244));
        chk3ch.setText("3 Cheese Loaded with Nachos Pizza....................520/-");
        chk3ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3chActionPerformed(evt);
            }
        });

        chkpan.setBackground(new java.awt.Color(16, 34, 63));
        chkpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkpan.setForeground(new java.awt.Color(244, 244, 244));
        chkpan.setText("Paneer Tikka Masala...................................................380/-");
        chkpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkpanActionPerformed(evt);
            }
        });

        chkmat.setBackground(new java.awt.Color(16, 34, 63));
        chkmat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkmat.setForeground(new java.awt.Color(244, 244, 244));
        chkmat.setText("Matar Palak....................................................................120/-");
        chkmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmatActionPerformed(evt);
            }
        });

        chkkor.setBackground(new java.awt.Color(16, 34, 63));
        chkkor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkkor.setForeground(new java.awt.Color(244, 244, 244));
        chkkor.setText("Chicken Korma..............................................................220/-");
        chkkor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkkorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 67, 71));
        jLabel4.setText("TOTAL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 67, 71));
        jLabel5.setText("TAX");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 67, 71));
        jLabel6.setText("SUB-TOTAL");

        subtxt.setBackground(new java.awt.Color(16, 34, 63));
        subtxt.setForeground(new java.awt.Color(255, 255, 255));
        subtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxtxt.setBackground(new java.awt.Color(16, 34, 63));
        taxtxt.setForeground(new java.awt.Color(255, 255, 255));
        taxtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totaltxt.setBackground(new java.awt.Color(16, 34, 63));
        totaltxt.setForeground(new java.awt.Color(255, 255, 255));
        totaltxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(233, 67, 71));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblconfor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblconfor.setForeground(new java.awt.Color(16, 34, 63));
        lblconfor.setText("      CONFIRM ORDER");
        lblconfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblconforMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblconfor, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblconfor, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(16, 34, 63));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblclror.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblclror.setForeground(new java.awt.Color(233, 67, 71));
        lblclror.setText("   CLEAR ORDER");
        lblclror.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 67, 71)));
        lblclror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclrorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblclror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblclror, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(16, 34, 63));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblsee.setForeground(new java.awt.Color(233, 67, 71));
        lblsee.setText("        SEE BILL");
        lblsee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 67, 71)));
        lblsee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblseeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblsee, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 67, 71));
        jLabel1.setText("  Username");

        txtusername.setBackground(new java.awt.Color(16, 34, 63));
        txtusername.setForeground(new java.awt.Color(244, 244, 244));
        txtusername.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(233, 67, 71));
        jSeparator1.setForeground(new java.awt.Color(233, 67, 71));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkmat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chktri)
                                        .addComponent(chkegg_l)
                                        .addComponent(chkcor)
                                        .addComponent(jLabel2))
                                    .addGap(34, 34, 34))
                                .addComponent(chkpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chkkor, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkgri)
                            .addComponent(chkand)
                            .addComponent(chk3ch))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(125, 125, 125)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtxt)
                                    .addComponent(totaltxt)
                                    .addComponent(taxtxt)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(358, 358, 358))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chktri, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkegg_l, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkcor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(taxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkmat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkkor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkand, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkgri, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk3ch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jMenuBar1.setBackground(new java.awt.Color(233, 67, 71));
        jMenuBar1.setForeground(new java.awt.Color(233, 67, 71));

        jMenu1.setText("Lunch Details");

        jMenu2.setText("Veg Triple Fried Rice");

        jMenuItem1.setText("Triple rice is complete meal with combination of rice, hakka noodles and fried noodles which is served with spicy schezwan manchurian gravy.");
        jMenu2.add(jMenuItem1);

        jMenu1.add(jMenu2);

        jMenu3.setText("Egg Schezwan Fried Rice");

        jMenuItem2.setText(" Schezwan fried rice is hot & spicy with bursting flavors of ginger, garlic, soya sauce & red chilli paste along with egg.");
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);

        jMenu4.setText("Chicken Coriander Rice with Gravy");

        jMenuItem3.setText("Fried rice is a dish of cooked rice that has been stir-fried in a wok or a frying pan, with flavor of coriander and spiced chicken.");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenu5.setText("Paneer Tikka Masala");

        jMenuItem4.setText("If you prefer a smooth curry, pass it through a sieve/ filter. pureed onion tomatoes for paneer tikka masala.");
        jMenu5.add(jMenuItem4);

        jMenu1.add(jMenu5);

        jMenu6.setText("Matar Palak");

        jMenuItem5.setText(" Palak Matar is a healthy combination of fresh green leafy spinach and green peas made into a curry.");
        jMenu6.add(jMenuItem5);

        jMenu1.add(jMenu6);

        jMenu7.setText("Chicken Korma");

        jMenuItem6.setText("Korma or qorma is a dish originating in the Indian subcontinent, consisting of meat or vegetables braised with yogurt (dahi) or cream, water or stock, and spices to produce a thick sauce or glaze");
        jMenu7.add(jMenuItem6);

        jMenu1.add(jMenu7);

        jMenu8.setText("Chicken and Cheese Burger");

        jMenuItem7.setText("A chicken Burger is a Burger that typically consists of boneless, skinless chicken breast ");
        jMenu8.add(jMenuItem7);

        jMenu1.add(jMenu8);

        jMenu9.setText("Veg Cheese Grilled Sandwich");

        jMenuItem8.setText("A veg sandwich is a sandwich that typically consists of fresh veggies and layers of cheese. ");
        jMenu9.add(jMenuItem8);

        jMenu1.add(jMenu9);

        jMenu10.setText("3 Cheese Loaded with Nachos Pizza");

        jMenuItem9.setText("Nachos Pizza is an interesting snack recipe that every kid would love to enjoy. Made with crispy nachos and thick layer of cheddar cheese.");
        jMenu10.add(jMenuItem9);

        jMenu1.add(jMenu10);

        jMenuBar1.add(jMenu1);

        jMenu11.setText("More...");

        jMenuItem10.setText("Go Back");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem10);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chktriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chktriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chktriActionPerformed

    private void chkegg_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkegg_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkegg_lActionPerformed

    private void chkcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkcorActionPerformed

    private void chkandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkandActionPerformed

    private void chkpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkpanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void chkmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkmatActionPerformed

    private void chkkorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkkorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkkorActionPerformed

    private void chkgriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkgriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkgriActionPerformed

    private void chk3chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3chActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk3chActionPerformed

    private void lblseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblseeMouseClicked
        // SEE BILL
        bill();
    }//GEN-LAST:event_lblseeMouseClicked

    private void lblclrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclrorMouseClicked
        // CLEAR BILL
        clearbill();
    }//GEN-LAST:event_lblclrorMouseClicked

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // GO BACK
        dispose();
        new Main_UI().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void lblconforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblconforMouseClicked
        // PLACE ORDER
        if(validation()==true)
        {
        bill();
        insertintodb();
        
        }
    }//GEN-LAST:event_lblconforMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lunch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk3ch;
    private javax.swing.JCheckBox chkand;
    private javax.swing.JCheckBox chkcor;
    private javax.swing.JCheckBox chkegg_l;
    private javax.swing.JCheckBox chkgri;
    private javax.swing.JCheckBox chkkor;
    private javax.swing.JCheckBox chkmat;
    private javax.swing.JCheckBox chkpan;
    private javax.swing.JCheckBox chktri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblclror;
    private javax.swing.JLabel lblconfor;
    private javax.swing.JLabel lblsee;
    private javax.swing.JTextField subtxt;
    private javax.swing.JTextField taxtxt;
    private javax.swing.JTextField totaltxt;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
